import {allows,matchesRules,metrics,type Rules} from './analysis';
export type Draw={round:number;date:string;numbers:number[];bonus:number;prize?:number;winners?:number};
export type Ticket={id:string;numbers:number[];round:number;created:string;method:string};
export const ALL=Array.from({length:45},(_,i)=>i+1);
export const sum=(ns:number[])=>ns.reduce((a,b)=>a+b,0);
export const odd=(ns:number[])=>ns.filter(n=>n%2).length;
export const pairs=(ns:number[])=>ns.filter((n,i)=>i>0&&n===ns[i-1]+1).length;
export function validNumbers(n:unknown):n is number[]{return Array.isArray(n)&&n.length===6&&new Set(n).size===6&&n.every(x=>Number.isInteger(x)&&x>=1&&x<=45)}
export function validDraw(d:Draw){return d&&Number.isInteger(d.round)&&d.round>0&&validNumbers(d.numbers)&&Number.isInteger(d.bonus)&&d.bonus>=1&&d.bonus<=45&&!d.numbers.includes(d.bonus)&&/^\d{4}-\d{2}-\d{2}/.test(d.date)}
export function stats(draws:Draw[],period:number){const subset=draws.slice(0,period);return ALL.map(n=>({n,count:subset.filter(d=>d.numbers.includes(n)).length,gap:draws.findIndex(d=>d.numbers.includes(n))<0?draws.length:draws.findIndex(d=>d.numbers.includes(n))}));}
export function rank(ns:number[],d:Draw){const hits=ns.filter(n=>d.numbers.includes(n)).length;const bonus=ns.includes(d.bonus);return {hits,bonus,rank:hits===6?1:hits===5&&bonus?2:hits===5?3:hits===4?4:hits===3?5:0};}
export function random(){const a=new Uint32Array(1);crypto.getRandomValues(a);return a[0]/4294967296;}
export function generate(draws:Draw[],opts:{method:string;count:number;include:number[];exclude:number[];oddFilter:string;noConsecutive:boolean;period:number;rules?:Rules}){const data=stats(draws,opts.period);const out:number[][]=[];const keys=new Set<string>();for(let attempts=0;attempts<20000&&out.length<opts.count;attempts++){const ns=[...opts.include];while(ns.length<6){const pool=ALL.filter(n=>!ns.includes(n)&&!opts.exclude.includes(n));const weights=pool.map(n=>opts.method==='hot'?data[n-1].count+1:opts.method==='cold'?data[n-1].gap+1:opts.method==='rare'?Math.max(...data.map(x=>x.count))+1-data[n-1].count:1);let r=random()*sum(weights);let picked=pool[pool.length-1];for(let i=0;i<pool.length;i++){r-=weights[i];if(r<0){picked=pool[i];break}}ns.push(picked)}ns.sort((a,b)=>a-b);if(opts.method==='balanced'&&(odd(ns)<2||odd(ns)>4||sum(ns)<100||sum(ns)>180))continue;if(opts.method==='spread'&&metrics(ns).zones<4)continue;if(opts.method==='repeat'&&metrics(ns,draws[0].numbers).repeat!==1)continue;if(opts.method==='pattern'&&(metrics(ns).ac<7||metrics(ns).ends<5||metrics(ns).zones<3||odd(ns)<2||odd(ns)>4||sum(ns)<100||sum(ns)>180))continue;if(!matchesRules(ns,draws[0]?.numbers??[],opts.rules??{}))continue;if(opts.rules?.maxShared!==undefined&&out.some(row=>row.filter(n=>ns.includes(n)).length>opts.rules!.maxShared!))continue;if(opts.rules?.sharedCounts?.length&&out.some(row=>!allows(opts.rules!.sharedCounts,row.filter(n=>ns.includes(n)).length)))continue;if(opts.oddFilter!=='any'&&odd(ns)!==Number(opts.oddFilter))continue;if(opts.noConsecutive&&pairs(ns)>0)continue;const key=ns.join(',');if(!keys.has(key)){keys.add(key);out.push(ns)}}return out}
export function expectedRound(now=new Date()){return Math.max(1,Math.floor((now.getTime()-Date.parse('2002-12-07T20:45:00+09:00'))/604800000)+2)}
export function drawDate(round:number){return new Date(Date.parse('2002-12-07T20:45:00+09:00')+(round-1)*604800000)}
